settings:
  target: "http://localhost"
#  target: "https://familyhome-api.azurewebsites.net"
#  target: "https://blank.org"
  report: "html"
  # Different phases
  phases:
    # This will spawn 10 users every second, for 5 seconds
    - arrivalRate: 10       # VU (virtual users) per second
      duration: 5           # 5 seconds
      

scenarios:
  - name: "Load test"
    flow:
      - get:
#          url: "/"
          url: "/test/get"
#          url: "/api/Garbage/scores?sinceDate=2022-01-01"